//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation_SupplierRoomTypeMapping_Values
    {
        public System.Guid Accommodation_SupplierRoomTypeMapping_Value_Id { get; set; }
        public Nullable<System.Guid> Accommodation_SupplierRoomTypeMapping_Id { get; set; }
        public int MapId { get; set; }
        public Nullable<System.Guid> Accommodation_RoomInfo_Id { get; set; }
        public Nullable<double> MatchingScore { get; set; }
        public string UserMappingStatus { get; set; }
        public string SystemMappingStatus { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_User { get; set; }
        public string Edit_SystemUser { get; set; }
        public Nullable<System.DateTime> SystemEditDate { get; set; }
        public Nullable<System.DateTime> UserEditDate { get; set; }
    }
}
