//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation_SupplierRoomTypeAttributes
    {
        public System.Guid RoomTypeMapAttribute_Id { get; set; }
        public System.Guid RoomTypeMap_Id { get; set; }
        public string SupplierRoomTypeAttribute { get; set; }
        public string SystemAttributeKeyword { get; set; }
        public System.Guid SystemAttributeKeyword_Id { get; set; }
        public Nullable<System.Guid> Accommodation_RoomFacility_Id { get; set; }
    }
}
