//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation_PaxOccupancy
    {
        public System.Guid Accommodation_PaxOccupancy_Id { get; set; }
        public Nullable<System.Guid> Accommodation_Id { get; set; }
        public Nullable<int> Legacy_Htl_Id { get; set; }
        public string RoomDisplayNumber { get; set; }
        public Nullable<System.Guid> Accommodation_RoomInfo_Id { get; set; }
        public Nullable<int> MaxAdults { get; set; }
        public Nullable<int> MaxPaxWithExtraBed { get; set; }
        public Nullable<int> MaxCNB { get; set; }
        public Nullable<int> MaxChild { get; set; }
        public Nullable<int> MaxPax { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> FromAgeForExtraBed { get; set; }
        public Nullable<int> ToAgeForExtraBed { get; set; }
        public Nullable<int> FromAgeForCNB { get; set; }
        public Nullable<int> ToAgeForCNB { get; set; }
        public Nullable<int> FromAgeForCIOR { get; set; }
        public Nullable<int> ToAgeForCIOR { get; set; }
        public string category { get; set; }
        public string companyName { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
