//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation_RoomInfo : IDisposable
    {
        public System.Guid Accommodation_RoomInfo_Id { get; set; }
        public Nullable<System.Guid> Accommodation_Id { get; set; }
        public Nullable<int> Legacy_Htl_Id { get; set; }
        public string RoomId { get; set; }
        public string RoomView { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> NoOfInterconnectingRooms { get; set; }
        public string Description { get; set; }
        public string RoomSize { get; set; }
        public string RoomDecor { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public string FloorName { get; set; }
        public string FloorNumber { get; set; }
        public Nullable<bool> MysteryRoom { get; set; }
        public string BathRoomType { get; set; }
        public string BedType { get; set; }
        public string CompanyRoomCategory { get; set; }
        public string RoomCategory { get; set; }
        public string Category { get; set; }
        public string CompanyName { get; set; }
        public string AmenityTypes { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TLGXAccoRoomId { get; set; }

        #region IDisposable Support

        private bool disposedValue = false; // To detect redundant calls

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    // TODO: dispose managed state (managed objects).
                }

                // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                // TODO: set large fields to null.

                disposedValue = true;
            }
        }

        // TODO: override a finalizer only if Dispose(bool disposing) above has code to free unmanaged resources.
        // ~Accommodation_RoomInfo() {
        //   // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
        //   Dispose(false);
        // }

        // This code added to correctly implement the disposable pattern.
        public void Dispose()
        {
            // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
            Dispose(true);
            // TODO: uncomment the following line if the finalizer is overridden above.
            // GC.SuppressFinalize(this);
        }
        #endregion
    }
}
