//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation_RouteInfo
    {
        public System.Guid Accommodation_Route_Id { get; set; }
        public Nullable<System.Guid> Accommodation_Id { get; set; }
        public Nullable<int> Legacy_Htl_Id { get; set; }
        public string DistanceFromProperty { get; set; }
        public string ApproximateDuration { get; set; }
        public string Description { get; set; }
        public string DrivingDirection { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string DistanceUnit { get; set; }
        public string AccommodationCode { get; set; }
        public string FromPlace { get; set; }
        public string NameOfPlace { get; set; }
        public string ModeOfTransport { get; set; }
        public string TransportType { get; set; }
        public string CompanyName { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
