//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation_RoomInfo_Attributes
    {
        public System.Guid Accommodation_RoomInfo_Attribute_Id { get; set; }
        public System.Guid Accommodation_RoomInfo_Id { get; set; }
        public string Accommodation_RoomInfo_Attribute { get; set; }
        public string SystemAttributeKeyword { get; set; }
        public System.Guid SystemAttributeKeyword_Id { get; set; }
    }
}
