//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_DaysOfWeek
    {
        public System.Guid Activity_DaysOfWeek_ID { get; set; }
        public System.Guid Activity_Flavor_ID { get; set; }
        public Nullable<System.Guid> Activity_DaysOfOperation_Id { get; set; }
        public string SupplierFrequency { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tues { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thur { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public string SupplierStartTime { get; set; }
        public string StartTime { get; set; }
        public string SupplierEndTime { get; set; }
        public string EndTime { get; set; }
        public string SupplierDuration { get; set; }
        public string Duration { get; set; }
        public string SupplierSession { get; set; }
        public string Session { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
