//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_ClassificationAttributes
    {
        public System.Guid Activity_ClassificationAttribute_Id { get; set; }
        public Nullable<System.Guid> Activity_Id { get; set; }
        public string AttributeType { get; set; }
        public string AttributeValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<bool> InternalOnly { get; set; }
        public string AttributeSubType { get; set; }
        public Nullable<System.Guid> Activity_Flavour_Id { get; set; }
        public Nullable<int> Legacy_Product_ID { get; set; }
        public Nullable<System.Guid> Activity_FlavourOptions_Id { get; set; }
    }
}
