//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_FlavourOptions
    {
        public System.Guid Activity_FlavourOptions_Id { get; set; }
        public Nullable<System.Guid> Activity_Flavour_Id { get; set; }
        public string Activity_FlavourName { get; set; }
        public string Activity_OptionName { get; set; }
        public string Activity_OptionCode { get; set; }
        public string Activity_Type { get; set; }
        public string Activity_DealText { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Create_User { get; set; }
        public string Edit_User { get; set; }
        public string TLGXActivityOptionCode { get; set; }
        public string Activity_LanguageCode { get; set; }
        public string Activity_Language { get; set; }
        public string Activity_OptionDescription { get; set; }
    }
}
