//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_PickupDropSchedule
    {
        public System.Guid Activity_PickupDropSchedule_Id { get; set; }
        public Nullable<System.Guid> Activity_Id { get; set; }
        public Nullable<int> Legacy_Product_Id { get; set; }
        public Nullable<System.Guid> Activity_Flavour_Id { get; set; }
        public string ForSupplier { get; set; }
        public Nullable<System.Guid> Supplier_Id { get; set; }
        public string SupplierName { get; set; }
    }
}
