//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Media
    {
        public System.Guid Activity_Media_Id { get; set; }
        public Nullable<System.Guid> Activity_Id { get; set; }
        public Nullable<int> Legacy_Product_Id { get; set; }
        public string MediaName { get; set; }
        public string MediaType { get; set; }
        public string RoomCategory { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Media_Path { get; set; }
        public string Media_URL { get; set; }
        public Nullable<int> Media_Position { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Description { get; set; }
        public string FileFormat { get; set; }
        public string MediaID { get; set; }
        public string MediaFileMaster { get; set; }
        public Nullable<System.Guid> Activity_Flavour_Id { get; set; }
        public Nullable<int> Media_Width { get; set; }
        public Nullable<int> Media_Height { get; set; }
        public string Media_Caption { get; set; }
    }
}
