//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_CategoriesType
    {
        public System.Guid Activity_CategoriesType_ID { get; set; }
        public System.Guid Activity_Flavour_Id { get; set; }
        public Nullable<System.Guid> Activity_FlavourOptions_Id { get; set; }
        public string SupplierProductCategory { get; set; }
        public string SupplierProductCategorySubType { get; set; }
        public string SupplierProductType { get; set; }
        public string SupplierProductNameSubType { get; set; }
        public string SystemProductCategory { get; set; }
        public string SystemProductCategorySubType { get; set; }
        public string SystemProductType { get; set; }
        public string SystemProductNameSubType { get; set; }
        public Nullable<System.Guid> SystemProductCategory_ID { get; set; }
        public Nullable<System.Guid> SystemProductCategorySubType_ID { get; set; }
        public Nullable<System.Guid> SystemProductType_ID { get; set; }
        public Nullable<System.Guid> SystemProductNameSubType_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Create_User { get; set; }
        public string Edit_User { get; set; }
    }
}
