//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_SupplierCityDepartureCode
    {
        public System.Guid DepartureID { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public string Hotel { get; set; }
        public string HotelCode { get; set; }
        public string DepartureCode { get; set; }
        public string DepartureName { get; set; }
    }
}
