//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Prices
    {
        public System.Guid Activity_Prices_Id { get; set; }
        public Nullable<System.Guid> Activity_Flavour_Id { get; set; }
        public Nullable<System.Guid> Activity_Id { get; set; }
        public string PriceCode { get; set; }
        public string PriceBasis { get; set; }
        public Nullable<decimal> PriceNet { get; set; }
        public string PriceCurrency { get; set; }
    }
}
