//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_DeparturePoints
    {
        public System.Guid Activity_DeparturePoints_ID { get; set; }
        public Nullable<System.Guid> Activity_Flavor_ID { get; set; }
        public Nullable<System.Guid> Activity_DaysOfOperation_Id { get; set; }
        public Nullable<System.Guid> Activity_DaysOfWeek_ID { get; set; }
        public string DepartureCode { get; set; }
        public string DeparturePoint { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
