//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public System.Guid Counter_Id { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> LastCounterNo { get; set; }
        public Nullable<int> IncreaseBy { get; set; }
    }
}
