//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicAttribute
    {
        public System.Guid DynamicAttribute_Id { get; set; }
        public string ObjectType { get; set; }
        public string AttributeClass { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public Nullable<System.Guid> Object_Id { get; set; }
        public Nullable<System.Guid> ObjectSubElement_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
    }
}
