//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Approval_StatusFlow
    {
        public System.Guid Approval_Status_Flow_ID { get; set; }
        public Nullable<System.Guid> Object_ID { get; set; }
        public string Object_Type { get; set; }
        public Nullable<System.Guid> Status_id { get; set; }
        public string Status { get; set; }
        public string Status_Message { get; set; }
        public string Next_Actor { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
