//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_CityMapping_EntityCount
    {
        public System.Guid EntityCityMapping_Id { get; set; }
        public Nullable<System.Guid> CityMapping_Id { get; set; }
        public string EntityType { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
    }
}
