//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_CountryMaster
    {
        public System.Guid Country_Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_User { get; set; }
        public string ISOofficial_name_en { get; set; }
        public string ISO3166_1_Alpha_2 { get; set; }
        public string ISO3166_1_Alpha_3 { get; set; }
        public string ISO3166_1_M49 { get; set; }
        public string ISO3166_1_ITU { get; set; }
        public string MARC { get; set; }
        public string WMO { get; set; }
        public string DS { get; set; }
        public string Dial { get; set; }
        public string ISO4217_currency_alphabetic_code { get; set; }
        public string ISO4217_currency_country_name { get; set; }
        public string ISO4217_currency_minor_unit { get; set; }
        public string ISO4217_currency_name { get; set; }
        public string ISO4217_currency_numeric_code { get; set; }
        public string ISO3166_1_Capital { get; set; }
        public string ISO3166_1_Continent { get; set; }
        public string ISO3166_1_TLD { get; set; }
        public string ISO3166_1_Languages { get; set; }
        public string ISO3166_1_Geoname_ID { get; set; }
        public string ISO3166_1_EDGAR { get; set; }
        public string GooglePlaceID { get; set; }
    }
}
