//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_keyword_alias
    {
        public System.Guid KeywordAlias_Id { get; set; }
        public Nullable<System.Guid> Keyword_Id { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_User { get; set; }
        public string Status { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> NoOfHits { get; set; }
    }
}
