//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_masterattribute
    {
        public System.Guid MasterAttribute_Id { get; set; }
        public string Name { get; set; }
        public string MasterFor { get; set; }
        public Nullable<System.Guid> ParentAttribute_Id { get; set; }
        public string OTA_CodeTableCode { get; set; }
        public string OTA_CodeTableName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
