//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_masterattributevalue
    {
        public System.Guid MasterAttributeValue_Id { get; set; }
        public Nullable<System.Guid> MasterAttribute_Id { get; set; }
        public Nullable<System.Guid> ParentAttributeValue_Id { get; set; }
        public string AttributeValue { get; set; }
        public string OTA_CodeTableValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MasterAttribute_Name { get; set; }
    }
}
