//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_PortMaster
    {
        public System.Guid m_Port_Id { get; set; }
        public string OAG_loc { get; set; }
        public string OAG_multicity { get; set; }
        public string OAG_type { get; set; }
        public string OAG_subtype { get; set; }
        public string oag_name { get; set; }
        public string oag_portname { get; set; }
        public string oag_ctry { get; set; }
        public string oag_subctry { get; set; }
        public string oag_ctryname { get; set; }
        public string oag_state { get; set; }
        public string oag_substate { get; set; }
        public string oag_timediv { get; set; }
        public string oag_lat { get; set; }
        public string oag_lon { get; set; }
        public string oag_inactive { get; set; }
        public Nullable<System.Guid> Country_Id { get; set; }
        public Nullable<System.Guid> State_Id { get; set; }
        public Nullable<System.Guid> City_Id { get; set; }
        public string MappingStatus { get; set; }
        public Nullable<System.Guid> MultiCity_Id { get; set; }
    }
}
