//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public System.Guid Place_Id { get; set; }
        public string Place_Category { get; set; }
        public string Name { get; set; }
        public string Formatted_Address { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Google_Place_Id { get; set; }
        public Nullable<double> Google_Rating { get; set; }
        public string Google_Reference { get; set; }
        public string Google_PlaceTypes { get; set; }
        public string Google_Icon { get; set; }
        public string Google_FullObjext { get; set; }
    }
}
