//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitemapInRole
    {
        public System.Guid SitemapInRoles_Id { get; set; }
        public System.Guid Sitemap_Id { get; set; }
        public System.Guid Role_Id { get; set; }
    }
}
