//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_ActivitySupplierProductMapping
    {
        public System.Guid stg_ActivitySupplierProductMappingId { get; set; }
        public string SupplierName { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string ActivityId { get; set; }
        public string FullResponse { get; set; }
        public string ResponseFormat { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string Status { get; set; }
        public string FullMediaResponse { get; set; }
        public string FullReviewResponse { get; set; }
    }
}
