//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_SupplierCityMapping
    {
        public System.Guid stg_City_Id { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string ActiveFrom { get; set; }
        public string ActiveTo { get; set; }
        public string UpdateType { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public string Action { get; set; }
        public string ActionText { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.Guid> Country_Id { get; set; }
        public Nullable<System.Guid> Supplier_Id { get; set; }
        public Nullable<System.Guid> SupplierImportFile_Id { get; set; }
    }
}
