//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_SupplierCountryMapping
    {
        public System.Guid stg_Country_Id { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string ActiveFrom { get; set; }
        public string ActiveTo { get; set; }
        public string Action { get; set; }
        public string UpdateType { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ActionText { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ContinentCode { get; set; }
        public string ContinentName { get; set; }
        public Nullable<System.Guid> SupplierImportFile_Id { get; set; }
    }
}
