//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_SupplierProductMapping
    {
        public System.Guid stg_AccoMapping_Id { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public string CountryCode { get; set; }
        public string CityCode { get; set; }
        public string Location { get; set; }
        public string ActiveFrom { get; set; }
        public string ActiveTo { get; set; }
        public string Action { get; set; }
        public string ActionText { get; set; }
        public string UpdateType { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public string StreetName { get; set; }
        public string Street2 { get; set; }
        public string PostalCode { get; set; }
        public string Street3 { get; set; }
        public string Street4 { get; set; }
        public string Street5 { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string StreetNo { get; set; }
        public string TX_COUNTRYNAME { get; set; }
    }
}
