//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Mapping_TableIds
    {
        public System.Guid STG_Mapping_Table_Id { get; set; }
        public Nullable<System.Guid> STG_Id { get; set; }
        public Nullable<System.Guid> Mapping_Id { get; set; }
        public Nullable<System.Guid> File_Id { get; set; }
    }
}
