//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_SupplierHotelRoomMapping
    {
        public System.Guid stg_SupplierHotelRoomMapping_Id { get; set; }
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierProductId { get; set; }
        public string SupplierProductName { get; set; }
        public string BathRoomType { get; set; }
        public string RoomDescription { get; set; }
        public Nullable<int> MaxAdults { get; set; }
        public Nullable<int> MaxChild { get; set; }
        public Nullable<int> MaxInfant { get; set; }
        public Nullable<int> MaxGuestOccupancy { get; set; }
        public string SupplierRoomId { get; set; }
        public string RoomViewCode { get; set; }
        public string SupplierRoomTypeCode { get; set; }
        public string RoomSize { get; set; }
        public string FloorName { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public string SupplierProvider { get; set; }
        public string Amenities { get; set; }
        public string Quantity { get; set; }
        public string RoomLocationCode { get; set; }
        public Nullable<int> ChildAge { get; set; }
        public string ExtraBed { get; set; }
        public string Bedrooms { get; set; }
        public string Smoking { get; set; }
        public string PromotionalVendorCode { get; set; }
        public string RoomName { get; set; }
        public string SupplierRoomCategory { get; set; }
        public string SupplierRoomCategoryId { get; set; }
        public string BeddingConfig { get; set; }
        public string BedTypeCode { get; set; }
        public string RatePlan { get; set; }
        public string RatePlanCode { get; set; }
        public string TX_RoomName { get; set; }
        public Nullable<System.Guid> Supplier_Id { get; set; }
        public string SupplierRoomTypeName { get; set; }
        public Nullable<int> MinGuestOccupancy { get; set; }
    }
}
