//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierImportFile_VerboseLog
    {
        public System.Guid SupplierImportFile_VerboseLog_Id { get; set; }
        public Nullable<System.Guid> SupplierImportFile_Id { get; set; }
        public string Step { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
