//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierImportFile_Statistics
    {
        public System.Guid SupplierImportFile_Statistics_Id { get; set; }
        public Nullable<System.Guid> SupplierImportFile_Id { get; set; }
        public string FinalStatus { get; set; }
        public Nullable<int> TotalRows { get; set; }
        public Nullable<int> Mapped { get; set; }
        public Nullable<int> Unmapped { get; set; }
        public Nullable<System.DateTime> Process_Date { get; set; }
        public string Process_User { get; set; }
    }
}
