//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierImportFile_ErrorLog
    {
        public System.Guid SupplierImportFile_ErrorLog_Id { get; set; }
        public System.Guid SupplierImportFile_Id { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public string ErrorType { get; set; }
        public Nullable<System.DateTime> Error_DATE { get; set; }
        public string Error_USER { get; set; }
    }
}
