//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_APILocation
    {
        public System.Guid Supplier_APILocation_Id { get; set; }
        public Nullable<System.Guid> Supplier_Id { get; set; }
        public Nullable<System.Guid> Entity_Id { get; set; }
        public string API_Path { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_USER { get; set; }
        public string STATUS { get; set; }
    }
}
