//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Scheduled_Task_Log
    {
        public System.Guid Log_Id { get; set; }
        public Nullable<System.Guid> Task_Id { get; set; }
        public string Status_Message { get; set; }
        public string Log_Type { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
