//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierImportFile_Progress
    {
        public System.Guid SupplierImportFileProgress_Id { get; set; }
        public Nullable<System.Guid> SupplierImportFile_Id { get; set; }
        public string Step { get; set; }
        public Nullable<int> PercentageValue { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalBatch { get; set; }
        public Nullable<int> CurrentBatch { get; set; }
        public Nullable<System.DateTime> LastCheckedOn { get; set; }
    }
}
